name: bestplace
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8472158017102629
  lightness: 0.15089281369000673
  saturation: 0.24647563183680177
  rhythmicContrast: 0.8837734221015126
purpose: []
